Feature/api
VovanShaitan/task-manager pull request #13
Opened 2022-10-26 05:53 UTC by VovanShaitan

При прогоне тестов выдает следующую ошибку:

Failure:
Api::V1::TasksControllerTest#test_should_post_create [/task_manager/test/controllers/api/v1/tasks_controller_test.rb:29]:
--- expected
+++ actual
@@ -1 +1 @@
-{"name"=>"string99", "description"=>"MyText", "state"=>"new_task", "expired_at"=>Wed, 26 Oct 2022, "assignee_id"=>1416}
+{"name"=>"string99", "description"=>"MyText", "state"=>"new_task", "expired_at"=>nil, "assignee_id"=>1416}

Почему возвращает nil? В фабрике на expired_at стояла статичная дата. Поменял на Date.current. Ок. Но почему из текущей даты значение не извлекается, не пойму.

Моя тупить и не понимать где в 29-й строке зарыта бяка...

2022-10-26 07:06 UTC, greybutton commented
надо разобраться какие параметры отправляется в тесте, какие приходят в контроллер, с каким создается таска. в общем, по всем шагам пройтись и там найдете причину

2022-10-27 16:57 UTC, greybutton requested changes

2022-10-27 16:57 UTC, greybutton commented on app/controllers/api/v1/application_controller.rb
> +  respond_to :html, :xml, :json
почему :html, :xml?

2022-10-27 16:57 UTC, greybutton commented on test/factories/tasks.rb
> -    expired_at
фикс не корректный. он фиксит, но не лучшим образом)

2022-10-27 17:56 UTC, VovanShaitan commented on app/controllers/api/v1/application_controller.rb
> +  respond_to :html, :xml, :json
В одной из ссылок на теорию охватывали все подряд. Получилось дорого-богато ) Понятно, что нам интересен лишь json.

2022-10-31 03:44 UTC, VovanShaitan commented
> надо разобраться какие параметры отправляется в тесте, какие приходят в контроллер, с каким создается таска. в общем, по всем шагам пройтись и там найдете причину

Безбожно туплю с поиском косяка третьи сутки. Причем в чате недавно девушка решила вопрос так же радикально, как и я (снесла expired_at и state), а в предыдущем потоке Артем Партос так же посоветовал убрать эту строку. Или я не так понял суть диалога двухгодичной давности. Но в любом случае сносить не дело, иначе теряется суть проверки. Дальше искал по рекомендованному логичному маршруту поиска ошибки. Но скорее всего мои рассуждения были вообще не там и не о том. Имею следующее:

Failure:
Api::V1::TasksControllerTest#test_should_post_create [/task_manager/test/controllers/api/v1/tasks_controller_test.rb:29]:
--- expected
+++ actual
@@ -1 +1 @@
-{"name"=>"string41", "description"=>"MyText", "state"=>"new_task", "expired_at"=>Mon, 31 Oct 2022, "assignee_id"=>3697}
+{"name"=>"string41", "description"=>"MyText", "state"=>"new_task", "expired_at"=>nil, "assignee_id"=>3697}

Строка 29 выглядит так:
assert_equal task_attributes.stringify_keys, created_task.slice(*task_attributes.keys)

Из фактори-бота должно приходит все согласно сиквенсам плюс мерджим assignee_id. Ок.
Далее мы создаем таску уже из app. Метод task_params возвращает (:name, :description, :author_id, :assignee_id, :state_event). Вот уже очень даже возможная причина почему nil. 
И в методе create мы используем метод respond_with(task, serializer: TaskSerializer, location: nil), который использует атрибуты attributes :id, :name, :description, :state, :expired_at, :transitions. Ждет expired_at, но не получает.

Я в том направлении хотя бы размышляю? Добавил в task_params expired_at, тесты проходят, но сейчас я уже вообще ни в чем не уверен )))

2022-10-31 06:41 UTC, greybutton approved these changes
да, все верно в пермитах потеряли параметр

2022-10-31 07:07 UTC, merged